ADD_SCENE(nfc_comparator, main_menu, MainMenu)
ADD_SCENE(nfc_comparator, select_nfc_card, SelectNfcCard)
ADD_SCENE(nfc_comparator, physical_scan, PhysicalScan)
ADD_SCENE(nfc_comparator, physical_results, PhysicalResults)
ADD_SCENE(nfc_comparator, digital_scan, DigitalScan)
ADD_SCENE(nfc_comparator, digital_results, DigitalResults)
ADD_SCENE(nfc_comparator, failed_to_load_nfc_card, FailedToLoadNfcCard)
