// Code generated by go-swagger; DO NOT EDIT.

// Package restapi NFC Analysis Platform API
//
//	API for NFC Analysis Platform
//	Schemes:
//	  http
//	  https
//	Host: localhost
//	BasePath: /api
//	Version: 1.0.0
//	License: GNU Affero General Public License v3.0 https://www.gnu.org/licenses/agpl-3.0.en.html
//	Contact: SpenserCai https://github.com/spensercai
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
