#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <chief_cooker_icons.h>

#include "app/App.cpp"

using namespace std;

// static void menuCallback(void* context, uint32_t index) {
//     UNUSED(index);

//     Submenu* menu = (Submenu*)context;
//     submenu_change_item_label(menu, index, "You pressed me");
// }

// static uint32_t menuBackCallback(void* context) {
//     UNUSED(context);
//     return VIEW_NONE;
// }

extern "C" int32_t chief_cooker_app(void* p) {
    UNUSED(p);

    App* app = new App();
    app->Run();
    /*
    Gui* gui = (Gui*)furi_record_open(RECORD_GUI);
    ViewDispatcher* viewDispatcher = view_dispatcher_alloc();
    view_dispatcher_attach_to_gui(viewDispatcher, gui, ViewDispatcherTypeFullscreen);

    Submenu* menu = submenu_alloc();
    submenu_set_header(menu, "Chief Cooker");
    submenu_add_item(menu, "Scan", 0, menuCallback, menu);
    submenu_add_item(menu, "Staion database", 1, menuCallback, menu);

    view_dispatcher_add_view(viewDispatcher, 0, submenu_get_view(menu));
    view_dispatcher_switch_to_view(viewDispatcher, 0);
    view_set_previous_callback(submenu_get_view(menu), menuBackCallback);

    view_dispatcher_run(viewDispatcher);

    view_dispatcher_remove_view(viewDispatcher, 0);
    view_dispatcher_free(viewDispatcher);
    submenu_free(menu);
    furi_record_close(RECORD_GUI);
*/
    return 0;
}
