#include <furi.h>
#include <gui/gui.h>

/* generated by fbt from .png files in images folder */
#include <furious_birds_icons.h>

typedef struct {
    FuriMutex* mutex;
} AppState;

static void game_draw_callback(Canvas* canvas, void* ctx) {
    AppState* appState = (AppState*)ctx;
    furi_mutex_acquire(appState->mutex, FuriWaitForever);

    canvas_clear(canvas);
    canvas_draw_icon(canvas, 20, 35, &I_Slingshot);
    canvas_draw_icon(canvas, 0, 40, &I_Red);
    canvas_draw_icon(canvas, 50, 00, &I_Pig);
    canvas_draw_icon(canvas, 50, 20, &I_Pig);
    canvas_draw_icon(canvas, 50, 40, &I_Pig);
    canvas_draw_icon(canvas, 70, 20, &I_Pig);
    canvas_draw_icon(canvas, 70, 40, &I_Pig);
    canvas_draw_icon(canvas, 70, 00, &I_Pig);
    canvas_draw_icon(canvas, 90, 00, &I_Pig);
    canvas_draw_icon(canvas, 90, 20, &I_Pig);
    canvas_draw_icon(canvas, 90, 40, &I_Pig);

    furi_mutex_release(appState->mutex);
}

static void game_input_callback(InputEvent* input_event, void* ctx) {
    furi_assert(ctx);
    FuriMessageQueue* event_queue = ctx;

    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

int32_t furious_birds_app(void* p) {
    UNUSED(p);

    InputEvent event;
    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    AppState* appState = malloc(sizeof(AppState));
    appState->mutex = furi_mutex_alloc(FuriMutexTypeNormal);

    // Configure view port
    ViewPort* view_port = view_port_alloc();
    view_port_draw_callback_set(view_port, game_draw_callback, appState);
    view_port_input_callback_set(view_port, game_input_callback, event_queue);

    // Register view port in GUI
    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    bool isFinishing = false;
    while(!isFinishing) {
        furi_check(furi_message_queue_get(event_queue, &event, FuriWaitForever) == FuriStatusOk);

        if((event.type != InputTypeShort) && (event.type != InputTypeLong)) continue;

        furi_mutex_acquire(appState->mutex, FuriWaitForever);

        if(event.key == InputKeyBack) {
            isFinishing = true;
        }
        view_port_update(view_port);
        furi_mutex_release(appState->mutex);
    }

    furi_message_queue_free(event_queue);
    gui_remove_view_port(gui, view_port);
    view_port_free(view_port);
    furi_record_close(RECORD_GUI);

    // Should happen after freeing viewport because draw callback could try to acquire mutex.
    furi_mutex_free(appState->mutex);
    free(appState);

    return 0;
}
