#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <furious_birds_icons.h>

int32_t furious_birds_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm furious_birds!");

    return 0;
}
