#include "core/kernel.h"
#include "gui/modules/variable_item_list.h"
#include "gui/view.h"
#include "gui/view_dispatcher.h"
#include "settings_ui.h"
#include <gui/gui.h>
#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <fzspground_icons.h>

#include "planet.h"
#include "asteroid.h"
#include "background.h"
#include "settings.h"
#include "common.h"
#include <sys/types.h>

static void tick_cb(void* ctx) {
    View* view = (View*)ctx;

    double dt = (double)1.0 / (double)60.0;

    background_update(dt);
    planet_update_planets(dt);
    asteroid_update_asteroids(dt);
    debri_update(dt);

    view_commit_model(view, true);
}

void fzspground_update_callback(View* view, void* ctx) {
    UNUSED(view);
    UNUSED(ctx);
}

void fzspground_draw_callback(Canvas* canvas, void* ctx) {
    UNUSED(ctx);
    canvas_clear(canvas);

    background_draw(canvas);
    planet_draw_planets(canvas);
    asteroid_draw_asteroids(canvas);
    debri_draw(canvas);

    int num_debri = debri_list.size;
    char debri_count_str[16];
    snprintf(debri_count_str, sizeof(debri_count_str), "Debris: %d", num_debri);
}

void fzspground_enter_callback(void* ctx) {
    UNUSED(ctx);

    planet_init();
}

bool fzspground_input_callback(InputEvent* e, void* ctx) {
    UNUSED(ctx);

    if(e->type == InputTypeShort && e->key == InputKeyBack) {
        view_dispatcher_stop(view_dispatcher);
        return true;
    }

    if(e->type == InputTypeShort && e->key == InputKeyOk) {
        settings_ui_open(view_dispatcher);
    }

    return false;
}

int32_t fzspground_app(void* p) {
    UNUSED(p);

    srand(furi_get_tick() & 0xFFFFFFFF);

    Gui* gui = furi_record_open("gui");

    view_dispatcher = view_dispatcher_alloc();

    view_dispatcher_attach_to_gui(view_dispatcher, gui, ViewDispatcherTypeFullscreen);

    settings_init();
    background_init();
    planet_init();
    asteroid_init();
    debri_init();
    settings_ui_init();

    View* main_view = view_alloc();

    view_set_draw_callback(main_view, fzspground_draw_callback);
    view_set_update_callback(main_view, fzspground_update_callback);
    view_set_input_callback(main_view, fzspground_input_callback);
    view_set_enter_callback(main_view, fzspground_enter_callback);

    View* settings_ui_view = variable_item_list_get_view(settings_list);
    view_set_previous_callback(settings_ui_view, settings_ui_previous_callback);

    view_dispatcher_add_view(view_dispatcher, MAIN_VIEW_ID, main_view);
    view_dispatcher_add_view(view_dispatcher, SETTINGS_VIEW_ID, settings_ui_view);

    view_dispatcher_set_event_callback_context(view_dispatcher, main_view);
    view_dispatcher_set_tick_event_callback(view_dispatcher, tick_cb, 16);

    view_dispatcher_switch_to_view(view_dispatcher, MAIN_VIEW_ID);
    view_dispatcher_run(view_dispatcher);

    view_dispatcher_set_tick_event_callback(view_dispatcher, NULL, 0);
    view_dispatcher_set_event_callback_context(view_dispatcher, NULL);
    view_dispatcher_stop(view_dispatcher);

    view_dispatcher_remove_view(view_dispatcher, MAIN_VIEW_ID);
    view_dispatcher_remove_view(view_dispatcher, SETTINGS_VIEW_ID);

    view_free(main_view);
    settings_ui_clear();

    view_dispatcher_free(view_dispatcher);

    furi_record_close("gui");

    planet_clear();
    asteroid_clear();
    background_clear();
    debri_clear();
    settings_clear();

    return 0;
}
