#include <mizip_balance_editor.h>

/* generated by fbt from .png files in images folder */
#include <mizip_balance_editor_icons.h>

// This function is called when the user has pressed the Back key.
bool mizip_balance_editor_app_navigation_callback(void* context) {
    furi_assert(context);
    MiZipBalanceEditorApp* app = context;
    // Back means exit the application, which can be done by stopping the ViewDispatcher.
    view_dispatcher_stop(app->view_dispatcher);
    return true;
}

// This function is called when there are custom events to process.
bool mizip_balance_editor_app_custom_event_callback(void* context, uint32_t event) {
    furi_assert(context);
    MiZipBalanceEditorApp* app = context;
    // The event numerical value can mean different things (the application is responsible to uphold its chosen convention)
    // In this example, the only possible meaning is the view index to switch to.
    furi_assert(event < ViewIndexCount);
    // Switch to the requested view.
    view_dispatcher_switch_to_view(app->view_dispatcher, event);

    return true;
}

// This function is called when the user presses the "Switch View" button on the Widget view.
void mizip_balance_editor_app_button_callback(
    GuiButtonType button_type,
    InputType input_type,
    void* context) {
    furi_assert(context);
    MiZipBalanceEditorApp* app = context;
    // Only request the view switch if the user short-presses the Center button.
    if(button_type == GuiButtonTypeCenter && input_type == InputTypeShort) {
        // Request switch to the Submenu view via the custom event queue.
        view_dispatcher_send_custom_event(app->view_dispatcher, ViewIndexSubmenu);
    }
}

// This function is called when the user activates the "Switch View" submenu item.
void mizip_balance_editor_app_submenu_callback(void* context, uint32_t index) {
    furi_assert(context);
    MiZipBalanceEditorApp* app = context;
    // Only request the view switch if the user activates the "Switch View" item.
    if(index == SubmenuIndexDirectToTag) {
        // Request switch to the Widget view via the custom event queue.
        view_dispatcher_send_custom_event(app->view_dispatcher, ViewIndexWidget);
    } else if(index == SubmenuIndexEditMiZipFile) {
        DialogsFileBrowserOptions browser_options;
        dialog_file_browser_set_basic_options(&browser_options, NFC_APP_EXTENSION, &I_Nfc_10px);
        browser_options.base_path = NFC_APP_FOLDER;
        browser_options.hide_dot_files = true;
        //Show file browser
        dialog_file_browser_show(app->dialogs, app->filePath, app->filePath, &browser_options);
        //Check if file is MiZip file
        mizip_balance_editor_load_file(app);
        //Return to view, delete later
        view_dispatcher_send_custom_event(app->view_dispatcher, ViewIndexWidget);
    }
}

//Function to check if the file is a MiZip file
void mizip_balance_editor_load_file(MiZipBalanceEditorApp* app) {
    furi_assert(app);

    NfcDevice* nfc_device = nfc_device_alloc();
    nfc_device_load(nfc_device, furi_string_get_cstr(app->filePath));
    if(nfc_device_get_protocol(nfc_device) == NfcProtocolMfClassic) {
        //MiFare Classic
        //TODO Check if file is MiZip and load
    } else {
        //Invalid file
        //TODO Show error message and return to main menu
    }

    nfc_device_free(nfc_device);
}

// Application constructor function.
static MiZipBalanceEditorApp* mizip_balance_editor_app_alloc() {
    MiZipBalanceEditorApp* app = malloc(sizeof(MiZipBalanceEditorApp));
    // Access the GUI API instance.
    Gui* gui = furi_record_open(RECORD_GUI);
    app->filePath = furi_string_alloc_set(NFC_APP_FOLDER);
    // Create and initialize the Widget view.
    app->widget = widget_alloc();
    widget_add_string_multiline_element(
        app->widget,
        64,
        32,
        AlignCenter,
        AlignCenter,
        FontSecondary,
        furi_string_get_cstr(app->filePath));
    widget_add_button_element(
        app->widget,
        GuiButtonTypeCenter,
        "Switch View",
        mizip_balance_editor_app_button_callback,
        app);
    // Create and initialize the Submenu view.
    app->submenu = submenu_alloc();
    submenu_set_header(app->submenu, "MiZip Balance Editor");
    submenu_add_item(
        app->submenu,
        "Direct to tag",
        SubmenuIndexDirectToTag,
        mizip_balance_editor_app_submenu_callback,
        app);
    submenu_add_item(
        app->submenu,
        "Edit MiZip file",
        SubmenuIndexEditMiZipFile,
        mizip_balance_editor_app_submenu_callback,
        app);
    // Create the ViewDispatcher instance.
    app->view_dispatcher = view_dispatcher_alloc();
    // Let the GUI know about this ViewDispatcher instance.
    view_dispatcher_attach_to_gui(app->view_dispatcher, gui, ViewDispatcherTypeFullscreen);
    // Register the views within the ViewDispatcher instance. This alone will not show any of them on the screen.
    // Each view must have its own index to refer to it later (it is best done via an enumeration as shown here).
    view_dispatcher_add_view(app->view_dispatcher, ViewIndexWidget, widget_get_view(app->widget));
    view_dispatcher_add_view(
        app->view_dispatcher, ViewIndexSubmenu, submenu_get_view(app->submenu));
    // Set the custom event callback. It will be called each time a custom event is scheduled
    // using the view_dispatcher_send_custom_callback() function.
    view_dispatcher_set_custom_event_callback(
        app->view_dispatcher, mizip_balance_editor_app_custom_event_callback);
    // Set the navigation, or back button callback. It will be called if the user pressed the Back button
    // and the event was not handled in the currently displayed view.
    view_dispatcher_set_navigation_event_callback(
        app->view_dispatcher, mizip_balance_editor_app_navigation_callback);
    // The context will be passed to the callbacks as a parameter, so we have access to our application object.
    view_dispatcher_set_event_callback_context(app->view_dispatcher, app);

    app->dialogs = furi_record_open(RECORD_DIALOGS);

    return app;
}

// Application destructor function.
static void mizip_balance_editor_app_free(MiZipBalanceEditorApp* app) {
    // All views must be un-registered (removed) from a ViewDispatcher instance
    // before deleting it. Failure to do so will result in a crash.
    view_dispatcher_remove_view(app->view_dispatcher, ViewIndexWidget);
    view_dispatcher_remove_view(app->view_dispatcher, ViewIndexSubmenu);
    // Now it is safe to delete the ViewDispatcher instance.
    view_dispatcher_free(app->view_dispatcher);
    // Delete the views
    widget_free(app->widget);
    submenu_free(app->submenu);
    // End access to hte the GUI API.
    furi_record_close(RECORD_GUI);
    // Free the remaining memory.

    furi_record_close(RECORD_DIALOGS);
    app->dialogs = NULL;
    free(app);
}

static void mizip_balance_editor_app_run(MiZipBalanceEditorApp* app) {
    // Display the Widget view on the screen.
    view_dispatcher_switch_to_view(app->view_dispatcher, ViewIndexSubmenu);
    // This function will block until view_dispatcher_stop() is called.
    // Internally, it uses a FuriEventLoop (see FuriEventLoop examples for more info on this).
    view_dispatcher_run(app->view_dispatcher);
}

int32_t mizip_balance_editor_app(void* p) {
    UNUSED(p);

    MiZipBalanceEditorApp* app = mizip_balance_editor_app_alloc();
    mizip_balance_editor_app_run(app);
    mizip_balance_editor_app_free(app);

    return 0;
}
