#pragma once

#include <gui/gui.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/submenu.h>
#include <gui/modules/popup.h>
#include <gui/modules/loading.h>
#include <gui/modules/widget.h>
#include <notification/notification_messages.h>

/* generated by fbt from .png files in images folder */
#include <portal_of_flipper_icons.h>

#include "scenes/pof_scene.h"

#include "helpers/pof_usb.h"
#include "virtual_portal.h"

typedef struct PoFApp PoFApp;

struct PoFApp {
    Gui* gui;
    ViewDispatcher* view_dispatcher;
    SceneManager* scene_manager;
    NotificationApp* notifications;
    Submenu* submenu;
    Popup* popup;
    Loading* loading;
    Widget* widget;

    VirtualPortal* virtual_portal;

    PoFUsb* pof_usb;
    
};

typedef enum {
    PoFViewSubmenu,
    PoFViewWidget,
    PoFViewPopup,
    PoFViewLoading,
} PoFView;

void pof_start(PoFApp* app);
void pof_stop(PoFApp* app);
void pof_show_loading_popup(void* context, bool show);
