void save_aes_result(const char* text);
void save_aes_decrypt_result(const char* text);
void save_affine_result(const char* text);
void save_affine_decrypt_result(const char* text);
void save_atbash_result(const char* text);
void save_atbash_decrypt_result(const char* text);
void save_baconian_result(const char* text);
void save_baconian_decrypt_result(const char* text);
void save_beaufort_result(const char* text);
void save_beaufort_decrypt_result(const char* text);
void save_caesar_result(const char* text);
void save_caesar_decrypt_result(const char* text);
void save_playfair_result(const char* text);
void save_playfair_decrypt_result(const char* text);
void save_polybius_result(const char* text);
void save_polybius_decrypt_result(const char* text);
void save_railfence_result(const char* text);
void save_railfence_decrypt_result(const char* text);
void save_rc4_result(const char* text);
void save_rc4_decrypt_result(const char* text);
void save_rot13_result(const char* text);
void save_rot13_decrypt_result(const char* text);
void save_scytale_result(const char* text);
void save_scytale_decrypt_result(const char* text);
void save_vigenere_result(const char* text);
void save_vigenere_decrypt_result(const char* text);
void save_blake2_result(const char* text);
void save_fnv1a_result(const char* text);
void save_md5_result(const char* text);
void save_murmur3_result(const char* text);
void save_sip_result(const char* text);
void save_sha1_result(const char* text);
void save_sha224_result(const char* text);
void save_sha256_result(const char* text);
void save_sha384_result(const char* text);
void save_sha512_result(const char* text);
void save_xx_result(const char* text);
void save_base32_result(const char* text);
void save_base32_decrypt_result(const char* text);
void save_base58_result(const char* text);
void save_base58_decrypt_result(const char* text);
void save_base64_result(const char* text);
void save_base64_decrypt_result(const char* text);
char* load_aes();
char* load_aes_decrypt();
char* load_affine();
char* load_affine_decrypt();
char* load_atbash();
char* load_atbash_decrypt();
char* load_baconian();
char* load_baconian_decrypt();
char* load_beaufort();
char* load_beaufort_decrypt();
char* load_caesar();
char* load_caesar_decrypt();
char* load_playfair();
char* load_playfair_decrypt();
char* load_polybius();
char* load_polybius_decrypt();
char* load_railfence();
char* load_railfence_decrypt();
char* load_rc4();
char* load_rc4_decrypt();
char* load_rot13();
char* load_rot13_decrypt();
char* load_scytale();
char* load_scytale_decrypt();
char* load_vigenere();
char* load_vigenere_decrypt();
char* load_blake2();
char* load_fnv1a();
char* load_md5();
char* load_murmur3();
char* load_sip();
char* load_sha1();
char* load_sha224();
char* load_sha256();
char* load_sha384();
char* load_sha512();
char* load_xx();
char* load_base32();
char* load_base32_decrypt();
char* load_base58();
char* load_base58_decrypt();
char* load_base64();
char* load_base64_decrypt();
void save_result(const char* text, char* file_name);