/*
My first flipper application
Simple stroboscope which can be used to measure the speed of a rotating object.

The base code is taken from https://github.com/instantiator/flipper-zero-tutorial-app/

*/

#include <furi.h>

#include <gui/gui.h>
#include <gui/icon_i.h>
#include <gui/view_dispatcher.h>
#include <gui/scene_manager.h>
#include <gui/modules/menu.h>

#define TAG "stroboscope"

/* generated by fbt from .png files in images folder */
#include <stroboscope_icons.h>

/* names of scenes used by the app */
typedef enum {
    StroboscopeScene_MainMenu,
    StroboscopeScene_count
} StroboscopeScene;

/** ids for the types of view used by the app */
typedef enum {
    TestAppView_Menu,
} TestAppView;

/** the app context struct */
typedef struct {
    SceneManager* scene_manager;
    ViewDispatcher* view_dispatcher;
    Menu* menu;
} StroboscopeApp;

/** all custom events */
typedef enum {
    StroboscopeAppEvent_
} StroboscopeAppEvent;

/** initialise the scene manager with all handlers */
void test_app_scene_manager_init(StroboscopeApp* app) {
    FURI_LOG_T(TAG, "test_app_scene_manager_init");
    app->scene_manager = scene_manager_alloc(&test_app_scene_event_handlers, app);
}

StroboscopeApp* test_app_init() {
    FURI_LOG_T(TAG, "test_app_init");
    StroboscopeApp* app = malloc(sizeof(StroboscopeApp));
    test_app_scene_manager_init(app);
    test_app_view_dispatcher_init(app);
    return app;
}

void set_app_log_level() {
#ifdef FURI_DEBUG
    furi_log_set_level(FuriLogLevelTrace);
#else
    furi_log_set_level(FuriLogLevelInfo);
#endif
}

int32_t stroboscope_app(void* p) {
    UNUSED(p);
    set_app_log_level();

    FURI_LOG_I(TAG, "Test app starting...");
    StroboscopeApp* app = test_app_init();

    return 0;
}
