#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <uv_meter_as7331_icons.h>

int32_t uv_meter_as7331_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm uv_meter_as7331!");

    return 0;
}
