#pragma once

// Standard types
#include <stddef.h>   // size_t, NULL
#include <stdint.h>
#include <stdbool.h>

// SDK: brings in the opaque Icon typedef so our icon externs compile
#include <gui/icon.h>

// App core types (Protocol, Payload, Attack, Ctx, scene enums, helpers, etc.)
#include "../ble_spam.h"

// Icon extern declarations (objects are generated by uFBT from your assets)
#include "ble_spam_icons.h"

// Handy macro (only if not already provided by ble_spam.h or elsewhere)
#ifndef COUNT_OF
#define COUNT_OF(arr) (sizeof(arr) / sizeof((arr)[0]))
#endif