#pragma once

// Standard types
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>

// Flipper GUI: provides the opaque Icon type
#include <gui/icon.h>

// App core: defines Protocol, Payload, Attack, Ctx, enums, etc.
// (Keep this path/name matched to your repo; in your tree these types are from ble_spam.h)
#include "../ble_spam.h"

// Icon externs generated by uFBT from your assets
#include "ble_spam_icons.h"

// Small helper
#ifndef COUNT_OF
#define COUNT_OF(arr) (sizeof(arr) / sizeof((arr)[0]))
#endif