ADD_SCENE(nfc_eink, start, Start)
ADD_SCENE(nfc_eink, choose_type, ChooseType)
ADD_SCENE(nfc_eink, emulate, Emulate)
ADD_SCENE(nfc_eink, result_menu, ResultMenu)
ADD_SCENE(nfc_eink, result_image, ResultImage)
ADD_SCENE(nfc_eink, save_name, SaveName)
ADD_SCENE(nfc_eink, save_success, SaveSuccess)
ADD_SCENE(nfc_eink, file_select, FileSelect)
ADD_SCENE(nfc_eink, saved_menu, SavedMenu) ///TODO: think of a better scene name
ADD_SCENE(nfc_eink, write, Write)
ADD_SCENE(nfc_eink, write_done, WriteDone)
ADD_SCENE(nfc_eink, error, Error)
ADD_SCENE(nfc_eink, exit_confirm, ExitConfirm)