#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <p1x_morse_code_learning_toolkit_icons.h>

int32_t p1x_morse_code_learning_toolkit_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm p1x_morse_code_learning_toolkit!");

    return 0;
}
