name: "FAP: Build and lint"

on: [push, pull_request]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: 'ufbt: Build for Release branch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build udecard-app with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: release
      - name: Upload udecard-app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          skip-setup: true
          task: lint
