// Code generated by go-swagger; DO NOT EDIT.

package nard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/spensercai/nfc_apdu_runner/tools/nfc_analysis_platform/pkg/wapi/codegen/models"
)

// DecodeApduResponseOKCode is the HTTP code returned for type DecodeApduResponseOK
const DecodeApduResponseOKCode int = 200

/*
DecodeApduResponseOK Successful operation

swagger:response decodeApduResponseOK
*/
type DecodeApduResponseOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewDecodeApduResponseOK creates DecodeApduResponseOK with default headers values
func NewDecodeApduResponseOK() *DecodeApduResponseOK {

	return &DecodeApduResponseOK{}
}

// WithPayload adds the payload to the decode apdu response o k response
func (o *DecodeApduResponseOK) WithPayload(payload *models.APIResponse) *DecodeApduResponseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the decode apdu response o k response
func (o *DecodeApduResponseOK) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DecodeApduResponseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
