// Code generated by go-swagger; DO NOT EDIT.

package nard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFlipperDevicesHandlerFunc turns a function with the right signature into a get flipper devices handler
type GetFlipperDevicesHandlerFunc func(GetFlipperDevicesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFlipperDevicesHandlerFunc) Handle(params GetFlipperDevicesParams) middleware.Responder {
	return fn(params)
}

// GetFlipperDevicesHandler interface for that can handle valid get flipper devices params
type GetFlipperDevicesHandler interface {
	Handle(GetFlipperDevicesParams) middleware.Responder
}

// NewGetFlipperDevices creates a new http.Handler for the get flipper devices operation
func NewGetFlipperDevices(ctx *middleware.Context, handler GetFlipperDevicesHandler) *GetFlipperDevices {
	return &GetFlipperDevices{Context: ctx, Handler: handler}
}

/*
	GetFlipperDevices swagger:route GET /nard/flipper/devices nard getFlipperDevices

# Get available Flipper Zero devices

Returns a list of available Flipper Zero devices
*/
type GetFlipperDevices struct {
	Context *middleware.Context
	Handler GetFlipperDevicesHandler
}

func (o *GetFlipperDevices) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetFlipperDevicesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
