// Code generated by go-swagger; DO NOT EDIT.

package nard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetFormatTemplateContentParams creates a new GetFormatTemplateContentParams object
//
// There are no default values defined in the spec.
func NewGetFormatTemplateContentParams() GetFormatTemplateContentParams {

	return GetFormatTemplateContentParams{}
}

// GetFormatTemplateContentParams contains all the bound params for the get format template content operation
// typically these are obtained from a http.Request
//
// swagger:parameters getFormatTemplateContent
type GetFormatTemplateContentParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Custom directory to search for format templates
	  In: query
	*/
	Directory *string
	/*ID of the format template
	  Required: true
	  In: path
	*/
	FormatID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetFormatTemplateContentParams() beforehand.
func (o *GetFormatTemplateContentParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qDirectory, qhkDirectory, _ := qs.GetOK("directory")
	if err := o.bindDirectory(qDirectory, qhkDirectory, route.Formats); err != nil {
		res = append(res, err)
	}

	rFormatID, rhkFormatID, _ := route.Params.GetOK("format_id")
	if err := o.bindFormatID(rFormatID, rhkFormatID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindDirectory binds and validates parameter Directory from query.
func (o *GetFormatTemplateContentParams) bindDirectory(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Directory = &raw

	return nil
}

// bindFormatID binds and validates parameter FormatID from path.
func (o *GetFormatTemplateContentParams) bindFormatID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.FormatID = raw

	return nil
}
