// Code generated by go-swagger; DO NOT EDIT.

package nard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/spensercai/nfc_apdu_runner/tools/nfc_analysis_platform/pkg/wapi/codegen/models"
)

// GetFlipperDevicesOKCode is the HTTP code returned for type GetFlipperDevicesOK
const GetFlipperDevicesOKCode int = 200

/*
GetFlipperDevicesOK Successful operation

swagger:response getFlipperDevicesOK
*/
type GetFlipperDevicesOK struct {

	/*
	  In: Body
	*/
	Payload *models.APIResponse `json:"body,omitempty"`
}

// NewGetFlipperDevicesOK creates GetFlipperDevicesOK with default headers values
func NewGetFlipperDevicesOK() *GetFlipperDevicesOK {

	return &GetFlipperDevicesOK{}
}

// WithPayload adds the payload to the get flipper devices o k response
func (o *GetFlipperDevicesOK) WithPayload(payload *models.APIResponse) *GetFlipperDevicesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get flipper devices o k response
func (o *GetFlipperDevicesOK) SetPayload(payload *models.APIResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFlipperDevicesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
