// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApduResContent apdu res content
//
// swagger:model ApduResContent
type ApduResContent struct {

	// Content of the .apdures file
	Content string `json:"content,omitempty"`

	// ID of the .apdures file
	ID string `json:"id,omitempty"`

	// Name of the .apdures file
	Name string `json:"name,omitempty"`
}

// Validate validates this apdu res content
func (m *ApduResContent) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this apdu res content based on context it is used
func (m *ApduResContent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ApduResContent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApduResContent) UnmarshalBinary(b []byte) error {
	var res ApduResContent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
