// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DecodeRequest decode request
//
// swagger:model DecodeRequest
type DecodeRequest struct {

	// Whether to enable debug mode
	Debug *bool `json:"debug,omitempty"`

	// Content of the format template to use (alternative to format_id)
	FormatContent string `json:"format_content,omitempty"`

	// ID of the format template to use
	FormatID string `json:"format_id,omitempty"`

	// APDU response data to decode
	// Required: true
	ResponseData *string `json:"response_data"`
}

// Validate validates this decode request
func (m *DecodeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResponseData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DecodeRequest) validateResponseData(formats strfmt.Registry) error {

	if err := validate.Required("response_data", "body", m.ResponseData); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this decode request based on context it is used
func (m *DecodeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DecodeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DecodeRequest) UnmarshalBinary(b []byte) error {
	var res DecodeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
