// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FlipperDevice flipper device
//
// swagger:model FlipperDevice
type FlipperDevice struct {

	// ID of the Flipper Zero device
	ID string `json:"id,omitempty"`

	// Whether the device is connected via serial
	IsSerial bool `json:"is_serial,omitempty"`

	// Path to the Flipper Zero device
	Path string `json:"path,omitempty"`

	// Serial port for the Flipper Zero device
	SerialPort string `json:"serial_port,omitempty"`
}

// Validate validates this flipper device
func (m *FlipperDevice) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this flipper device based on context it is used
func (m *FlipperDevice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FlipperDevice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FlipperDevice) UnmarshalBinary(b []byte) error {
	var res FlipperDevice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
