// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TlvParseRequest tlv parse request
//
// swagger:model TlvParseRequest
type TlvParseRequest struct {

	// Hex TLV data to parse
	// Required: true
	HexData *string `json:"hex_data"`
}

// Validate validates this tlv parse request
func (m *TlvParseRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHexData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TlvParseRequest) validateHexData(formats strfmt.Registry) error {

	if err := validate.Required("hex_data", "body", m.HexData); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this tlv parse request based on context it is used
func (m *TlvParseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TlvParseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TlvParseRequest) UnmarshalBinary(b []byte) error {
	var res TlvParseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
