// Moon Phases by P1X
// This program calculates the current moon phase based on the current date
// Made for the Flipper Zero
// Images from NASA https://science.nasa.gov/moon/moon-phases/

#include <furi.h>
#include <gui/gui.h>
#include <gui/view.h>
#include <gui/view_dispatcher.h>
#include <notification/notification.h>
#include <notification/notification_messages.h>
#include <furi_hal_rtc.h>

/* generated by fbt from .png files in images folder */
#include <p1x_moon_phases_icons.h>

typedef enum {
    MoonPhaseNewMoon = 0,
    MoonPhaseWaxingCrescent,
    MoonPhaseFirstQuarter,
    MoonPhaseWaxingGibbous,
    MoonPhaseFullMoon,
    MoonPhaseWaningGibbous,
    MoonPhaseLastQuarter,
    MoonPhaseWaningCrescent,
    MoonPhaseCount
} MoonPhase;

typedef struct {
    ViewDispatcher* view_dispatcher;
    Gui* gui;
    NotificationApp* notifications;
    View* view;
} MoonPhasesApp;

// Calculate moon phase (0-7) based on current date
static MoonPhase get_moon_phase() {
    DateTime date;
    furi_hal_rtc_get_datetime(&date);

    // Calculating moon phase using the algorithm
    // Based on the formula from "Astronomical Algorithms" by Jean Meeus
    uint32_t year = date.year;
    uint8_t month = date.month;
    uint8_t day = date.day;

    // Adjust month and year for the formula
    if(month <= 2) {
        month += 12;
        year--;
    }

    // Calculate Julian date
    double jd = 365.25 * (year + 4716) + 30.6001 * (month + 1) + day - 1524.5;
    
    // Calculate moon phase (0-29.5 days)
    // 2451550.1 is the Julian date for the new moon on Jan 6, 2000
    double daysSinceNewMoon = fmod(jd - 2451550.1L, 29.53L);
    
    // Convert days to phase number (0-7)
    // Each phase is approximately 3.69 days
    MoonPhase phase = (MoonPhase)(daysSinceNewMoon / 3.69L);
    
    return phase < MoonPhaseCount ? phase : MoonPhaseNewMoon;
}

// Get icon for the current moon phase
static const Icon* get_moon_phase_icon(MoonPhase phase) {
    switch(phase) {
        case MoonPhaseNewMoon:
            return &I_new_moon;
        case MoonPhaseWaxingCrescent:
            return &I_waxing_crescent;
        case MoonPhaseFirstQuarter:
            return &I_first_quarter;
        case MoonPhaseWaxingGibbous:
            return &I_waxing_gibbous;
        case MoonPhaseFullMoon:
            return &I_full_moon;
        case MoonPhaseWaningGibbous:
            return &I_waning_gibbous;
        case MoonPhaseLastQuarter:
            return &I_last_quarter;
        case MoonPhaseWaningCrescent:
            return &I_waning_crescent;
        default:
            return &I_new_moon;
    }
}

// Get text description for the current moon phase
static const char* get_moon_phase_name(MoonPhase phase) {
    switch(phase) {
        case MoonPhaseNewMoon:
            return "New Moon";
        case MoonPhaseWaxingCrescent:
            return "Waxing Crescent";
        case MoonPhaseFirstQuarter:
            return "First Quarter";
        case MoonPhaseWaxingGibbous:
            return "Waxing Gibbous";
        case MoonPhaseFullMoon:
            return "Full Moon";
        case MoonPhaseWaningGibbous:
            return "Waning Gibbous";
        case MoonPhaseLastQuarter:
            return "Last Quarter";
        case MoonPhaseWaningCrescent:
            return "Waning Crescent";
        default:
            return "Unknown";
    }
}

// Custom view callback for drawing
static void moon_phases_view_draw_callback(Canvas* canvas, void* context) {
    UNUSED(context);
    
    // Fill background with black
    canvas_set_color(canvas, ColorBlack);
    canvas_draw_box(canvas, 0, 0, 128, 64);
    
    // Set text color to white
    canvas_set_color(canvas, ColorWhite);
    
    MoonPhase current_phase = get_moon_phase();
    const Icon* icon = get_moon_phase_icon(current_phase);
    const char* phase_name = get_moon_phase_name(current_phase);
    

    // Draw moon phase icon - centered (icon size is 48x46)
    // Cannot access icon->width directly, use hardcoded values as we know them
    canvas_set_color(canvas, ColorBlack);
    canvas_draw_icon(canvas, 64 - 24, 32 - 23, icon);  // 24 = 48/2, 23 = 46/2
    canvas_set_color(canvas, ColorWhite);

    // Draw phase name at top with primary font
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str_aligned(canvas, 64, 6, AlignCenter, AlignCenter, phase_name);
    
    DateTime date;
    furi_hal_rtc_get_datetime(&date);
    
    char date_str[32];
    snprintf(date_str, sizeof(date_str), "%02d/%02d/%d", date.day, date.month, date.year);
    
    // Add date at the bottom
    canvas_set_font(canvas, FontSecondary);
    canvas_draw_str_aligned(canvas, 64, 60, AlignCenter, AlignCenter, date_str);
}

static bool moon_phases_view_input_callback(InputEvent* event, void* context) {
    MoonPhasesApp* app = context;
    bool consumed = false;
    
    if(event->type == InputTypeShort && event->key == InputKeyBack) {
        view_dispatcher_stop(app->view_dispatcher);
        consumed = true;
    }
    
    return consumed;
}

// Clean up the application
static void moon_phases_app_free(MoonPhasesApp* app) {
    view_dispatcher_remove_view(app->view_dispatcher, 0);
    view_free(app->view);
    view_dispatcher_free(app->view_dispatcher);
    furi_record_close(RECORD_GUI);
    furi_record_close(RECORD_NOTIFICATION);
    free(app);
}

int32_t p1x_moon_phases_app(void* p) {
    UNUSED(p);
    
    // Allocate and initialize app structure
    MoonPhasesApp* app = malloc(sizeof(MoonPhasesApp));
    memset(app, 0, sizeof(MoonPhasesApp));
    
    // Open GUI record
    app->gui = furi_record_open(RECORD_GUI);
    app->notifications = furi_record_open(RECORD_NOTIFICATION);
    
    // Create view dispatcher
    app->view_dispatcher = view_dispatcher_alloc();
    
    // Create custom view
    app->view = view_alloc();
    view_set_context(app->view, app);
    view_set_draw_callback(app->view, moon_phases_view_draw_callback);
    view_set_input_callback(app->view, moon_phases_view_input_callback);
    
    // Add view to the view dispatcher
    view_dispatcher_add_view(app->view_dispatcher, 0, app->view);
    view_dispatcher_switch_to_view(app->view_dispatcher, 0);
    
    // Set GUI and view dispatcher
    view_dispatcher_attach_to_gui(
        app->view_dispatcher, app->gui, ViewDispatcherTypeFullscreen);
    
    // Main application loop
    notification_message(app->notifications, &sequence_display_backlight_on);
    
    view_dispatcher_run(app->view_dispatcher);
    
    // Clean up
    moon_phases_app_free(app);
    
    return 0;
}
