// Code generated by go-swagger; DO NOT EDIT.

package tlv

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	"github.com/spensercai/nfc_apdu_runner/tools/nfc_analysis_platform/pkg/wapi/codegen/models"
)

// NewParseTlvDataParams creates a new ParseTlvDataParams object
//
// There are no default values defined in the spec.
func NewParseTlvDataParams() ParseTlvDataParams {

	return ParseTlvDataParams{}
}

// ParseTlvDataParams contains all the bound params for the parse tlv data operation
// typically these are obtained from a http.Request
//
// swagger:parameters parseTlvData
type ParseTlvDataParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Parse request
	  Required: true
	  In: body
	*/
	ParseRequest *models.TlvParseRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewParseTlvDataParams() beforehand.
func (o *ParseTlvDataParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.TlvParseRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("parseRequest", "body", ""))
			} else {
				res = append(res, errors.NewParseError("parseRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ParseRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("parseRequest", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
