name: "FAP: Build all apps"

on:
  push:
  pull_request:
  schedule:
    - cron: "1 1 * * *"

jobs:
  ufbt-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: dev channel
            sdk-channel: dev
          - name: release channel
            sdk-channel: release
    name: 'ufbt: Build for ${{ matrix.name }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build badusb_pro
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: badusb_pro
      - name: Build ccid_emulator
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: ccid_emulator
          skip-setup: true
      - name: Build hid_exfil
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: hid_exfil
          skip-setup: true
      - name: Build nfc_fuzzer
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: nfc_fuzzer
          skip-setup: true
      - name: Build spi_flash_dump
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: spi_flash_dump
          skip-setup: true
      - name: Build subghz_spectrum
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: subghz_spectrum
          skip-setup: true
